name: test:e2e

concurrency:
  group: pr-workflow-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    
env:
  SERVICE: kyberswap-interface


jobs:
  e2e:
    runs-on: ubuntu-18.04
    container: cypress/browsers:node12.18.3-chrome87-ff82
    needs: install

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.18.1  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Gcloud Auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCR_CREDENTIALS }}'

      - name: Setup Gcloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Configure docker
        run: gcloud auth configure-docker

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ env.SERVICE }}-buildx

      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependences
        uses: bahmutov/npm-install@HEAD     

      - name: Test
        uses: cypress-io/github-action@v4.x.x
        with:
          install-command: yarn --frozen-lockfile --prefer-offline --no-audit
          command: yarn test:e2e